- hosts: all
  connection: local
  gather_facts: no
  become: no
  vars:
    # for ansible-role-mas
    mas_installed_apps:
      - { id: 497799835, name: "Xcode (10.1)" }
    # for ansible-role-dotfiles
    dotfiles_repo: "git@github.com:eichisanden/dotfiles.git"
    dotfiles_repo_local_destination: "~/src/github.com/eichisanden/dotfiles"
    dotfiles_files:
      - .bashrc
      - .eslintrc
      - .gitattributes
      - .gitconfig
      - .gitignore
      - .psqlrc
      - .vimrc
      - .zshrc

  tasks:
    - name: add tap repository to homebrew
      homebrew_tap: name={{ item }}
      with_items: 
        - mas-cli/tap

    - name: update homebrew
      homebrew: update_homebrew=yes

    - name: install homebrew cask packages
      homebrew_cask:
        name: "{{ item }}"
      with_items:
        - cheatsheet
        - clipy
        - docker
        - dropbox
        - evernote
        - firefox
        - google-chrome
        - intellij-idea
        - iterm2
        - jetbrains-toolbox
        - vagrant
        - virtualbox
        - visual-studio-code

    - name: install homebrew packages
      homebrew:
        name:
          - ansible
          - git
          - go
          - jq
          - mas
          - nkf
          - nodebrew
          - peco
          - python
          - rbenv
          - ruby-build
          - tree
          - wget
          - zsh

    - name: install vim
      homebrew:
        name:
          - vim
        install_options:
          --with-override-system-vi

    - name: 'check oh-my-zsh'
      stat: path=~/.oh-my-zsh/
      register: d 
    - name: 'install oh-my-zsh'
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      when: d.stat.exists == false
    - name: 'change default shell'
      user:
        name: "{{ ansible_ssh_user }}"
        shell: /usr/local/bin/zsh

  roles:
    - geerlingguy.mas
    - geerlingguy.dotfiles

