- hosts: all
  connection: local
  gather_facts: no
  become: no
  vars:
    mas_installed_apps:
      - { id: 497799835, name: "Xcode (10.1)" }

  tasks:
    - name: add tap repository to homebrew
      homebrew_tap: name={{ item }}
      with_items: 
        - mas-cli/tap

    - name: update homebrew
      homebrew: update_homebrew=yes

    - name: install homebrew cask packages
      homebrew_cask:
        name: "{{ item }}"
      with_items:
        - cheatsheet
        - clipy
        - docker
        - dropbox
        - evernote
        - firefox
        - google-chrome
        - intellij-idea
        - iterm2
        - jetbrains-toolbox
        - vagrant
        - virtualbox
        - visual-studio-code

    - name: install homebrew packages
      homebrew:
        name:
          - ansible
          - git
          - jq
          - mas
          - nkf
          - nodebrew
          - peco
          - python
          - tree
          - wget
          - zsh

    - name: install vim
      homebrew:
        name:
          - vim
        install_options:
          --with-override-system-vi

    - name: 'check oh-my-zsh'
      stat: path=~/.oh-my-zsh/
      register: d 
    - name: 'install oh-my-zsh'
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      when: d.stat.exists == false

  roles:
    - geerlingguy.mas
