- hosts: localhost
  connection: local
  gather_facts: no
  become: no

  tasks:
    - name: add tap repository to homebrew
      homebrew_tap:
        name: caskroom/cask

    - name: update homebrew
      homebrew: update_homebrew=yes

    - name: install homebrew cask packages
      homebrew_cask:
        name: "{{ item }}"
      with_items:
        - docker
        - evernote
        - firefox
        - google-chrome
        - intellij-idea
        - iterm2
        - jetbrains-toolbox
        - vagrant
        - virtualbox
        - visual-studio-code

    - name: install homebrew packages
      homebrew:
        name:
          - ansible
          - git
          - jq
          - nkf
          - nodebrew
          - peco
          - python
          - tree
          - wget
          - zsh

