- hosts: all
  connection: local
  gather_facts: no
  become: no
  vars:
    # for ansible-role-mas
    mas_installed_apps:
      - { id: 497799835, name: "Xcode (10.1)" }
    # for ansible-role-dotfiles
    dotfiles_repo: "git@github.com:eichisanden/dotfiles.git"
    dotfiles_repo_local_destination: "~/src/github.com/eichisanden/dotfiles"
    dotfiles_files:
      - .bashrc
      - .eslintrc
      - .gitattributes
      - .gitconfig
      - .gitignore
      - .psqlrc
      - .vimrc
      - .zshrc

  tasks:
    - name: add tap repository to homebrew
      homebrew_tap: name={{ item }}
      with_items: 
        - mas-cli/tap

    - name: update homebrew
      homebrew: update_homebrew=yes

    - name: install homebrew cask packages
      homebrew_cask:
        name: "{{ item }}"
      with_items:
        - cheatsheet
        - clipy
        - docker
        - dropbox
        - evernote
        - firefox
        - google-chrome
        - intellij-idea
        - iterm2
        - jetbrains-toolbox
        - opera
        - vagrant
        - virtualbox
        - visual-studio-code

    - name: install homebrew packages
      homebrew:
        name:
          - ansible
          - git
          - go
          - hugo
          - jq
          - mas
          - nkf
          - nodebrew
          - peco
          - python
          - rbenv
          - ruby-build
          - tree
          - wget
          - zsh

    - name: install vim
      homebrew:
        name:
          - vim
        install_options:
          --with-override-system-vi

    - name: 'check oh-my-zsh'
      stat: path=~/.oh-my-zsh/
      register: d 
    - name: 'install oh-my-zsh'
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      when: d.stat.exists == false
    - name: 'change default shell'
      user:
        name: "{{ ansible_ssh_user }}"
        shell: /usr/local/bin/zsh

    - name: 'setting macOS'
      osx_defaults: >
        domain={{ item.domain }}
        key={{ item.key }}
        type={{ item.type }}
        value={{ item.value }}
        state={{ item.state|default('present') }}
      with_items:
        # auto hide dock (need "killall Dock")
        - { domain: com.apple.dock, key: autohide, type: bool, value: true }
        - { domain: com.apple.dock, key: autohide-time-modifier, type: int, value: 0 }
        # Move dock to left side
        - { domain: com.apple.dock, key: orientation, type: string, value: "left" }
        # Show Status bar in Finder (need "killall Finder")
        - { domain: com.apple.finder, key: ShowStatusBar, type: bool, value: true }
        # Show Path bar in Finder
        - { domain: com.apple.finder, key: ShowPathbar, type: bool, value: true }
        # Show Tab bar in Finder
        - { domain: com.apple.finder, key: ShowTabView, type: bool, value: true }
        # Show the hidden files
        - { domain: com.apple.finder, key: AppleShowAllFiles, type: bool, value: true }
        # Enable text selection in QuickLook
        - { domain: com.apple.finder, key: QLEnableTextSelection, type: bool, value: true }
        # Show the battery percentage from the menu bar (need "killall SystemUIServer")
        - { domain: com.apple.menuextra.battery, key: ShowPercent, type: string, value: "YES" }

    - name: 'check dein'
      stat: path=~/.cache/dein
      register: d
    - name: 'install dein'
      shell: sh <(curl -fsSL https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh) ~/.cache/dein
      args:
        executable: /bin/bash  # for process substitution
      register: e
      when: d.stat.exists == false

  roles:
    - geerlingguy.mas
    - geerlingguy.dotfiles

