---
- hosts: all
  connection: local
  gather_facts: no
  become: no
  vars:
    # for ansible-role-mas
    mas_installed_apps:
      - { id: 497799835, name: "Xcode (10.1)" }
    # for ansible-role-dotfiles
    dotfiles_repo: "git@github.com:eichisanden/dotfiles.git"
    dotfiles_repo_local_destination: "~/src/github.com/eichisanden/dotfiles"
    dotfiles_files:
      - .bashrc
      - .eslintrc
      - .gitattributes
      - .gitconfig
      - .gitignore
      - .psqlrc
      - .vimrc
      - .zshrc

  tasks:
    - name: 'check dein'
      stat: path=~/.cache/dein
      register: d 
    - name: 'install dein'
      shell: sh <(curl -fsSL https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh) ~/.cache/dein
      args:
        executable: /bin/bash
      register: e
      when: d.stat.exists == false

      #    - debug:
      #  msg: "{{ e.stdout }}"
